
PASTA_ENTRADA = r"#######"

PASTA_RESULTADOS = r"######"

PASTA_ERROS_PDF = r"#######"

ARQUIVO_CONFIG_USUARIO = "config_user.txt"
ARQUIVO_HISTORICO = "historico.txt"
ARQUIVO_ERROS = "erros.txt"

TEMPO_ESPERA_ARQUIVO = 2

INTERVALO_MONITORAMENTO = 3

EXTENSAO_MONITORADA = ".pdf"
